wicket:
  external:
    agilcoders:
      bootstrap:
        theme: flatly
  core:
    settings:
      general:
        configuration-type: development
      requestcycle:
        timeout-size: 1
        timeout-unit: minutes
hibernate:
  hbm2ddl:
    auto: none
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/northwind
    username: root
    password: sepai123
    driver-class-name: com.mysql.jdbc.Driver
